language: node_js

node_js:
  - 9
  - 8
  - 6
  - 4

os:
  - linux
  - osx

branches:
  only:
    - master
    - /^greenkeeper.*$/

install:
  - travis_retry npm install

script:
  - npm run test

after_success:
  - npm run codecov

jobs:
  include:
    - stage: release
      node_js: lts/*
      os: linux
      script:
        - npm run semantic-release
